"""add age and gender to patients

Revision ID: 6e37cfbeab41
Revises: b462d65107fa
Create Date: 2026-04-11 14:57:56.683248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e37cfbeab41'
down_revision: Union[str, Sequence[str], None] = 'b462d65107fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'age')
    # ### end Alembic commands ###
