"""init tables

Revision ID: 7e025e35227c
Revises: 7f2c1a8e9d4b
Create Date: 2026-05-07 20:45:03.961919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e025e35227c'
down_revision: Union[str, Sequence[str], None] = '7f2c1a8e9d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('patients_email_key'), 'patients', type_='unique')
    op.drop_constraint(op.f('patients_phone_key'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=True)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.create_unique_constraint(op.f('patients_phone_key'), 'patients', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('patients_email_key'), 'patients', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
